### ISSUE TITLE
Create survey summary page

### ISSUE THREAD

**Issue by migurski** [codeforamerica/resident-web-use-research#1]
Make it look like this:

![survey](https://cloud.githubusercontent.com/assets/58730/6832871/4f81bb60-d2e6-11e4-8b32-711c9a3b53c7.png)

**Comment by boonrs** [comment]
So excited about this. Will there be a chance to select what to take into account on a recommendation? For example, [Boulder](http://censusreporter.org/profiles/16000US0807850-boulder-co/) doesn't have diverse ethnicity & race or languages. Outreach will focus on age, household income, and renter/owner status.

**Comment by migurski** [comment]
Yeah—I think benchmarking against who Census says lives in your city would be sufficient. Age/housing is a great one to add.

**Comment by migurski** [comment]
@jmadans points out “the response rate and maps might be much more intuitive if we ask cities to set response goals beforehand.” Should add target numbers.

**Comment by boonrs** [comment]
Ah, got it. Have I mentioned how excited I am about this? :fireworks: :tada:

**Comment by migurski** [comment]
:boom:

**Comment by prestonrhea** [comment]
To repeat what I shared with @boonrs and @migurski: similar to what @boonrs showed Boulder, it would be interesting for this tool to also compare and contrast the census data for a given city, and similar data for whatever group / circle is using the tool.

For example: I help run city council public hearings. I use the tool to select my city (Oakland), which automatically pulls in Oakland census data and displays it on the left. I also input a spreadsheet of data we've collected of who comes to city council public hearings, and this is displayed on the right. It's an immediate visual contrast of "who's the city, and who are we in this room?" Could be used by any group: churches, neighborhood gatherings, Brigades, etc. etc.

This would be really helpful for the "reach" part of civic engagement.

**Comment by migurski** [comment]
@prestonrhea, are there parts of http://censusreporter.org/profiles/16000US0653000-oakland-ca/ you would imagine being good for what you describe?

**Comment by prestonrhea** [comment]
@migurski yes absolutely. Maybe tailoring it down to some very specific categories, but in general yes.

**Comment by prestonrhea** [comment]
@migurski the main thing being, similar to how you have Map A and Map B up there - tailor it into Circle A (the whole of the city or region) and Circle B (the same categories as A but for your meeting / group / survey).

**Comment by hannahyoung** [comment]
@migurski this is awesome! will there be the ability to add in baseline data from different sources (i.e. city census, non-profits, etc)? for example, LGBTQI data isn't collected in the US Census but the CDC has good LGBTQI data.

**Comment by migurski** [comment]
@hannahyoung—hadn’t though of that, very interesting. What granularity is the CDC data?

**Comment by migurski** [comment]
Here’s where we’re at:

[survey-page-results.html](http://jekit.codeforamerica.org/codeforamerica/resident-web-use-research/21517ae/survey-page-results.html?gdoc=1QrizzwFTineFqjaTJ33HQTzdZklJMmJEBbYVaVfMeGU&cityname=Oakland%2C+CA)
(watch the `http` vs. `https` URLs, Chrome tries to SSL you but it needs to be `http`)

This will Good Enough™ for now and we can move on to improving information design, documenting [input spreadsheet format](https://docs.google.com/a/codeforamerica.org/spreadsheets/d/1QrizzwFTineFqjaTJ33HQTzdZklJMmJEBbYVaVfMeGU/pubhtml), and optimizing slow parts.
